version: "1"


services:
  postgresql:
    container_name: reviews_postgresql
    image: postgres:14
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: postgres1
      POSTGRES_DB: reviews
    volumes:
      - ./postgres-data:/data/
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge